version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app  # Монтируем текущую директорию
    ports:
      - "8000:8000"  # Прокси-порт
    env_file:
      - .env  # Если у вас есть файл с переменными окружения
    depends_on:
      - db
  db:
    image: postgres:latest
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}       # Укажите существующего пользователя из .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Укажите существующий пароль из .env
      POSTGRES_DB: ${POSTGRES_DB}
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - static_volume:/app/staticfiles
    depends_on:
      - web

volumes:
  postgres_data:
  static_volume: