version: '3.8'

services:
  web:
    build: .
    volumes:
      - .:/app  # Монтируем текущую директорию
    ports:
      - "8000:8000"  # Прокси-порт
    env_file:
      - .env  # Если у вас есть файл с переменными окружения