# Generated by Django 4.0.4 on 2024-08-20 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storageclientm2m',
            options={'verbose_name': 'Склад для клиента', 'verbose_name_plural': 'Склады для клиента'},
        ),
        migrations.AddField(
            model_name='storage',
            name='free_area',
            field=models.PositiveIntegerField(blank=True, default=0, verbose_name='Свободная площадь (кв.м.)'),
        ),
        migrations.AlterField(
            model_name='storageclientm2m',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='storageclientm2m',
            name='storage',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.storage', verbose_name='Склад'),
        ),
    ]
