# Generated by Django 5.1 on 2024-09-13 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_remove_itembooking_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrefund',
            name='count',
        ),
        migrations.RemoveField(
            model_name='itemrefund',
            name='item',
        ),
        migrations.AlterField(
            model_name='itembookingitemm2m',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_bookings', to='base.itembooking', verbose_name='Заявка на бронь*'),
        ),
        migrations.CreateModel(
            name='ItemRefundItemM2M',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_count', models.PositiveIntegerField(verbose_name='Количество*')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='refund_items', to='base.item', verbose_name='Товар*')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_refunds', to='base.itemrefund', verbose_name='Заявка на возврат*')),
            ],
            options={
                'verbose_name': 'Товар на возврат',
                'verbose_name_plural': 'Товары на возвраты',
            },
        ),
        migrations.AddField(
            model_name='itemrefund',
            name='items',
            field=models.ManyToManyField(related_name='refunds', through='base.ItemRefundItemM2M', to='base.item', verbose_name='Товары*'),
        ),
    ]
