# Generated by Django 5.1 on 2024-09-11 13:50

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_item_storage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemimage',
            options={'verbose_name': 'Фотография товара', 'verbose_name_plural': 'Фотографии товара'},
        ),
        migrations.AlterField(
            model_name='itemimage',
            name='image',
            field=models.ImageField(upload_to=base.models.get_image_upload_path, verbose_name='Фото'),
        ),
        migrations.CreateModel(
            name='ItemStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('existing', 'Заявка на существующий товар'), ('new', 'Заявка на новый товар')], max_length=10, verbose_name='Тип заявки')),
                ('new_item_name', models.CharField(blank=True, max_length=128, null=True, verbose_name='Название нового товара')),
                ('new_item_description', models.TextField(blank=True, null=True, verbose_name='Описание нового товара')),
                ('new_item_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Масса нового товара (кг)')),
                ('new_item_height', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Высота нового товара (см)')),
                ('new_item_width', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Ширина нового товара (см)')),
                ('new_item_length', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Длина нового товара (см)')),
                ('count', models.PositiveIntegerField(verbose_name='Количество')),
                ('existing_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_requests', to='base.item', verbose_name='Существующий товар')),
            ],
        ),
    ]
