# Generated by Django 5.1 on 2024-09-11 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_itemimage_options_alter_itemimage_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itemstock',
            options={'verbose_name': 'Заявка на приход товара', 'verbose_name_plural': 'Заявки на приход товара'},
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_approved',
        ),
        migrations.RemoveField(
            model_name='item',
            name='is_booked',
        ),
        migrations.AddField(
            model_name='itemstock',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подтверждение наличия'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='count',
            field=models.PositiveIntegerField(verbose_name='Количество*'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='request_type',
            field=models.CharField(choices=[('existing', 'Заявка на существующий товар'), ('new', 'Заявка на новый товар')], max_length=10, verbose_name='Тип заявки*'),
        ),
    ]
