# Generated by Django 5.1 on 2024-09-13 14:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_itemrefund_count_remove_itemrefund_item_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemimage',
            name='item_stock',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.itemstock', verbose_name='Приход товара'),
        ),
    ]
