# Generated by Django 5.1 on 2024-09-13 14:35

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_itemimage_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itembooking',
            options={'verbose_name': 'Заявка на бронь товаров', 'verbose_name_plural': 'Заявки на бронь товаров'},
        ),
        migrations.AlterModelOptions(
            name='itemrecovery',
            options={'verbose_name': 'Заявка на утилизацию', 'verbose_name_plural': 'Заявки на утилизацию'},
        ),
        migrations.AlterModelOptions(
            name='itemrefund',
            options={'verbose_name': 'Заявка на возвраты', 'verbose_name_plural': 'Заявки на возвраты'},
        ),
        migrations.CreateModel(
            name='RecoveryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.get_recovery_item_image_path, verbose_name='Фото*')),
                ('recovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.itemrecovery', verbose_name='Заявка на утилизацию')),
            ],
            options={
                'verbose_name': 'Фотография товара',
                'verbose_name_plural': 'Фотографии товара',
            },
        ),
    ]
