# Generated by Django 5.1 on 2024-09-14 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_alter_itembooking_options_alter_itemrecovery_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstock',
            name='new_item_arrival_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата прихода нового товара'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='new_item_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.itemcategory', verbose_name='Категория нового товара'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='new_item_client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.client', verbose_name='Клиент нового товара'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='new_item_expiration_date',
            field=models.DateField(blank=True, null=True, verbose_name='Срок годности (конечная дата) нового товара'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='new_item_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.project', verbose_name='Проект нового товара'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='new_item_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.itemstatus', verbose_name='Состояние нового товара'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='new_item_storage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.storage', verbose_name='Склад нового товара'),
        ),
        migrations.AlterField(
            model_name='item',
            name='arrival_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата прихода'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='is_approved',
            field=models.BooleanField(blank=True, default=False, verbose_name='Подтверждение наличия на складе'),
        ),
    ]
