# Generated by Django 5.1 on 2024-09-18 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_user_storages_alter_item_count_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itembookingitemm2m',
            options={'verbose_name': 'Товар на бронь', 'verbose_name_plural': 'Товары на бронь'},
        ),
        migrations.AddField(
            model_name='itemrecovery',
            name='count',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
    ]
