# Generated by Django 5.1 on 2024-09-18 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_alter_itembookingitemm2m_options_itemrecovery_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemrefund',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Город*'),
        ),
        migrations.AddField(
            model_name='itemrefund',
            name='end_date',
            field=models.DateField(null=True, verbose_name='Дата (по)*'),
        ),
        migrations.AddField(
            model_name='itemrefund',
            name='start_date',
            field=models.DateField(null=True, verbose_name='Дата (с)*'),
        ),
    ]
