# Generated by Django 5.1 on 2024-09-18 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_itemrefund_city_itemrefund_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrefund',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='itemrefund',
            name='start_date',
        ),
        migrations.AddField(
            model_name='itemrefund',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата возврата*'),
        ),
    ]
