# Generated by Django 5.1 on 2024-09-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_itemrefund_end_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconsumption',
            name='date',
            field=models.DateField(null=True, verbose_name='Дата отправки*'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='date_created',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата создания заявки'),
        ),
    ]
