# Generated by Django 5.1 on 2024-09-18 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0012_itemconsumption_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemconsumption',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Город (откуда едет)*'),
        ),
    ]
