# Generated by Django 5.1 on 2024-09-24 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_itemconsumption_city'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemstock',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='planning_date',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
