# Generated by Django 5.1 on 2024-09-25 14:17

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_itemstock_date_itemstock_planning_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_booked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Забронирован?'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Город (куда едет)*'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Фактическая дата'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='planning_date',
            field=models.DateField(default=datetime.datetime.now, verbose_name='Планируемая дата*'),
        ),
    ]
