# Generated by Django 5.1 on 2024-09-25 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0015_item_is_booked_alter_itemconsumption_city_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemrefund',
            name='status',
        ),
        migrations.AlterField(
            model_name='itemrefund',
            name='city',
            field=models.CharField(max_length=255, null=True, verbose_name='Город (куда едет)*'),
        ),
    ]
