# Generated by Django 5.1 on 2024-09-25 14:29

import base.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0016_remove_itemrefund_status_alter_itemrefund_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemRefundImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=base.models.get_refund_item_image_path, verbose_name='Фото*')),
                ('refund', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='base.itemrefund', verbose_name='Заявка на возврат')),
            ],
            options={
                'verbose_name': 'Фотография товаров',
                'verbose_name_plural': 'Фотографии товаров',
            },
        ),
    ]
