# Generated by Django 5.1 on 2024-09-28 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0019_itemconsumption_description_itemconsumptionimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='itembooking',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Архивировано/отработано'),
        ),
        migrations.AddField(
            model_name='itemconsumption',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Архивировано/отработано'),
        ),
        migrations.AddField(
            model_name='itemrecovery',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Архивировано/отработано'),
        ),
        migrations.AddField(
            model_name='itemrefund',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Архивировано/отработано'),
        ),
        migrations.AddField(
            model_name='itemstock',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Архивировано/отработано'),
        ),
    ]
