# Generated by Django 5.1 on 2024-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0020_itembooking_is_archived_itemconsumption_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembooking',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архивировано/отработано'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архивировано/отработано'),
        ),
        migrations.AlterField(
            model_name='itemrecovery',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архивировано/отработано'),
        ),
        migrations.AlterField(
            model_name='itemrefund',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архивировано/отработано'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архивировано/отработано'),
        ),
    ]
