# Generated by Django 5.1 on 2024-12-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0021_alter_itembooking_is_archived_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itembooking',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='itemconsumption',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='itemrecovery',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='itemrefund',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архив'),
        ),
        migrations.AlterField(
            model_name='itemstock',
            name='is_archived',
            field=models.BooleanField(blank=True, default=False, verbose_name='Архив'),
        ),
    ]
