name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH key
      run: |
        env
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 ${{ secrets.SSH_HOST_IP }} >> ~/.ssh/known_hosts
        sudo apt-get install sshpass

    # - name: Add known hosts
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.SSH_KNOWN_HOSTS }}" > ~/.ssh/known_hosts

    - name: Deploy to server
      run: |
        ssh ${{ secrets.SSH_USER}}@${{ secrets.SSH_HOST_IP}} "cd nozhenko_crm/ && git pull origin main && docker compose down && docker compose up -d --build"